"""add_llm_narrative_to_alerts

Adds three columns to the alerts table for LLM-generated explainability:
  - llm_narrative: Plain-English attack narrative generated by local LLM (Ollama/llama3)
  - llm_mitre_tactic: MITRE ATT&CK tactic name returned by the LLM
  - llm_mitre_technique: MITRE ATT&CK technique ID/name returned by the LLM

These are populated asynchronously by LLMAnalyzerService after alert creation.
All columns are nullable so existing alerts are unaffected.

Revision ID: a1b2c3d4e5f6
Revises: eaef4f9fe2a1
Create Date: 2026-02-19 00:00:00.000000

Ref: TDD Section 4.X LLM Analyzer, SRS FR-C010
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'eaef4f9fe2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('alerts', sa.Column('llm_narrative', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('llm_mitre_tactic', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('llm_mitre_technique', sa.String(), nullable=True))


def downgrade() -> None:
    op.drop_column('alerts', 'llm_mitre_technique')
    op.drop_column('alerts', 'llm_mitre_tactic')
    op.drop_column('alerts', 'llm_narrative')
