"""add_llm_remediation_to_alerts

Adds llm_remediation column to the alerts table for LLM-generated remediation steps.
  - llm_remediation: Numbered, actionable remediation steps generated by local LLM (Ollama/llama3)

Populated asynchronously by LLMAnalyzerService alongside existing llm_narrative.
Nullable so existing alerts are unaffected.

Revision ID: c3d4e5f6a7b8
Revises: a1b2c3d4e5f6
Create Date: 2026-02-21 00:00:00.000000

Ref: TDD Section 4.X LLM Analyzer, SRS FR-C010
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d4e5f6a7b8'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('alerts', sa.Column('llm_remediation', sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column('alerts', 'llm_remediation')
