
"""add_infra_nodes_table

Revision ID: d95109bc626d
Revises: dc897a5d941c
Create Date: 2026-02-19 14:14:18.874121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95109bc626d'
down_revision: Union[str, None] = 'dc897a5d941c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infra_nodes',
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('os_type', sa.String(), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('winrm_port', sa.Integer(), nullable=False),
    sa.Column('ssh_username', sa.String(), nullable=True),
    sa.Column('ssh_password_enc', sa.String(), nullable=True),
    sa.Column('ssh_key_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deployment_status', sa.String(), nullable=False),
    sa.Column('deployed_agent_type', sa.String(), nullable=True),
    sa.Column('deployed_agent_id', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('discovery_method', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infra_nodes_ip_address'), 'infra_nodes', ['ip_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_infra_nodes_ip_address'), table_name='infra_nodes')
    op.drop_table('infra_nodes')
    # ### end Alembic commands ###
