
"""add_mac_address_to_infra_nodes

Revision ID: eaef4f9fe2a1
Revises: d95109bc626d
Create Date: 2026-02-19 14:50:34.420172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaef4f9fe2a1'
down_revision: Union[str, None] = 'd95109bc626d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infra_nodes', sa.Column('mac_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('infra_nodes', 'mac_address')
    # ### end Alembic commands ###
