import logging
import ssl
from pathlib import Path
from typing import Optional

from nats.aio.client import Client as NATS
from nats.js import JetStreamContext

from ..config import settings

logger = logging.getLogger("n7-core.messaging")

# Certs generated by scripts/generate_certs_and_jwt.py and stored under n7_core/certs/
_CERTS_DIR = Path(__file__).parent.parent / "certs"


def _build_tls_context() -> Optional[ssl.SSLContext]:
    """Build an mTLS SSL context using the Core's generated client cert and CA."""
    ca_crt = _CERTS_DIR / "core-ca.crt"
    client_crt = _CERTS_DIR / "api-server.crt"
    client_key = _CERTS_DIR / "api-server.key"

    if not (ca_crt.exists() and client_crt.exists() and client_key.exists()):
        logger.warning("NATS mTLS certs not found — connecting without TLS (will fail against mTLS server)")
        return None

    ctx = ssl.create_default_context(ssl.Purpose.SERVER_AUTH, cafile=str(ca_crt))
    ctx.check_hostname = False  # NATS server cert SAN is 'localhost', not a hostname
    ctx.load_cert_chain(certfile=str(client_crt), keyfile=str(client_key))
    return ctx


class NATSClient:
    """
    NATS Client wrapper with auto-reconnect and JetStream support.
    Ref: TDD Section 3.1 & 7.1
    """

    def __init__(self):
        self.nc = NATS()
        self.js: Optional[JetStreamContext] = None

    async def connect(self):
        """
        Connects to NATS cluster with resilience settings.
        Initializes JetStream and creates the events stream if it doesn't exist.
        """
        from nats.js.errors import NotFoundError
        from nats.js.api import StreamConfig

        tls_ctx = _build_tls_context()

        try:
            await self.nc.connect(
                servers=[settings.NATS_URL],
                name=settings.NATS_CLIENT_ID,
                tls=tls_ctx,
                reconnect_time_wait=2,
                max_reconnect_attempts=-1,  # Infinite reconnects
                error_cb=self._error_cb,
                disconnected_cb=self._disconnected_cb,
                reconnected_cb=self._reconnected_cb,
            )
            self.js = self.nc.jetstream()
            
            # Create the reliable event stream
            try:
                await self.js.stream_info("EVENTS_STREAM")
                logger.info("JetStream EVENTS_STREAM already exists.")
            except NotFoundError:
                await self.js.add_stream(name="EVENTS_STREAM", subjects=["n7.events.>"])
                logger.info("Created JetStream EVENTS_STREAM.")

            logger.info(f"Connected to NATS at {settings.NATS_URL} with JetStream enabled.")
        except Exception as e:
            logger.error(f"Failed to connect to NATS or initialize JetStream: {e}")
            raise

    async def close(self):
        """
         gracefully closes the NATS connection.
        """
        if self.nc.is_connected:
            await self.nc.drain()
            logger.info("NATS connection closed.")

    async def _error_cb(self, e):
        logger.error(f"NATS Error: {e}")

    async def _disconnected_cb(self):
        logger.warning("Disconnected from NATS...")

    async def _reconnected_cb(self):
        logger.info("Reconnected to NATS!")


nats_client = NATSClient()
